name: Build slides
on:
  - pull_request
jobs:
  build:
    name: Build slides
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: reviewdog/action-languagetool@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: info
    - name: misspell
      uses: reviewdog/action-misspell@v1
      with:
        github_token: ${{ secrets.REVIEWDOG_TOKEN }}
        locale: "US"
        reporter: github-pr-check
    - run: sudo apt install pandoc graphviz texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - run: make
